### ISSUE TITLE
Metadata Item Icons wont register

### ISSUE THREAD

**Issue by skully250** [skully250/FullmetalAlchemy-Dev#1]
Metadata Item Icons wont register, but they wont not register(not become a black and purple box) either need this fixed, and unsure of how to do it myself (yes i have tried shadow -_-)

**Comment by zpiddock** [comment]
word of advice, dont post issues on your own repo

**Comment by Darkhax** [comment]
This ^

**Comment by skully250** [comment]
:P i did it to get your attention but it didnt work

**Comment by zpiddock** [comment]
it did, i was busy the day i saw it though
